jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite:
          - testplan.xml
          - requirement.xml
          - authortest.xml
          - main.xml
    name: Run TestNG Suite ${{ matrix.suite }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install -DskipTests

      - name: Run TestNG Suite - ${{ matrix.suite }}
        run: |
          mvn test \
            -DsuiteXmlFile=TestRun_XML/${{ matrix.suite }} \
            -Dbrowser=chrome \
            -Dmode=headless \
            -DlogName=${{ matrix.suite }}

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-${{ matrix.suite }}
          path: target/surefire-reports/

      - name: Upload Extent HTML Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-html-reports-${{ matrix.suite }}
          path: reports/
