name: CI - Run TestNG Suites with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - suite: testplan.xml
            logName: testPlan
          - suite: requirement.xml
            logName: requirementLog
          - suite: authortest.xml
            logName: authorLog
          - suite: main.xml
            logName: mainLog

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install -DskipTests

      - name: Run TestNG Suite - ${{ matrix.suite }}
        continue-on-error: true
        run: |
          mvn test \
            -DsuiteXmlFile=TestRun_XML/${{ matrix.suite }} \
            -Dbrowser=chrome \
            -Dmode=headless \
            -DlogName=${{ matrix.logName }}
      

      - name: Upload Surefire Reports - ${{ matrix.suite }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-${{ matrix.suite }}
          path: target/surefire-reports/

      - name: Upload Extent HTML Reports - ${{ matrix.suite }}
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-html-reports-${{ matrix.suite }}
          path: reports/
