name: CI - Run TestNG Suites with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B clean install -DskipTests

      - name: Run TestNG - Main Suite
        run: mvn test -DsuiteXmlFile=TestRun_XML/testplan.xml -Dbrowser=chrome -Dmode=local

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Upload Extent HTML Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-html-reports
          path: reports/
